# Generated by Django 4.1.7 on 2023-05-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'page_manager',
            '0002_image_delete_url_image_extension_image_thumbnail_url_and_more'  # noqa
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
