# Generated by Django 4.1.7 on 2023-05-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_manager', '0002_alter_page_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
