# flake8: noqa
# Generated by Django 4.1.7 on 2023-05-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_manager', '0003_component_section_sectionvalue_componentvalue_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_page', to='page_manager.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='component_page', to='page_manager.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentvalue',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page_manager.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionvalue',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page_manager.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_section', to='page_manager.section'),
        ),
        migrations.AlterField(
            model_name='component',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_column', to='page_manager.page'),
        ),
    ]
