# Generated by Django 4.1.7 on 2023-05-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'page_manager',
            '0004_column_page_component_page_componentvalue_page_and_more'
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnValue',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                (
                    'column',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='page_manager.column'
                    )
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='page_manager.page'
                    )
                ),
            ],
            options={
                'unique_together': {('column', 'key')},
            },
        ),
    ]
