# Generated by Django 4.1.7 on 2023-05-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_manager', '0005_columnvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='column',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='component_column',
                to='page_manager.column'
            ),
        ),
    ]
