FROM python:3.10-alpine

RUN apk add build-base gcompat libstdc++

RUN wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
RUN chmod +x tailwindcss-linux-x64
RUN mv tailwindcss-linux-x64 /bin/tailwindcss
RUN alias tailwindcss=/bin/tailwindcss