--- # yamllint disable-line
version: "3.9"

services:
  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pagemanager
    # networks:
    #   - dbnetwork
    restart: always
  website:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      - SITE=website
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pagemanager
    working_dir: /app/project
    volumes:
      - media:/app/project/media/
      - static:/app/project/static/
      - .:/app/
    command: sh -c 'python manage.py check --deploy && python manage.py collectstatic --noinput && gunicorn project.asgi:application -b 0.0.0.0:8080 -k uvicorn.workers.UvicornWorker' # yamllint disable-line
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
    links:
      - database:database
      # networks:
      #   - dbnetwork
      #   - webnetwork
  cms:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    environment:
      - SITE=cms
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pagemanager
    working_dir: /app/project
    volumes:
      - media:/app/project/media/
      - static:/app/project/static/
      - .:/app/
    command: sh -c 'python manage.py check --deploy && python manage.py collectstatic --noinput && gunicorn project.asgi:application -b 0.0.0.0:8080 -k uvicorn.workers.UvicornWorker' # yamllint disable-line
    ports:
      - "8000:8080"
    depends_on:
      - database
    restart: always
    links:
      - database:database
      # networks:
      #   - dbnetwork
      #   - webnetwork
  assets:
    build:
      context: ./
      dockerfile: Dockerfile.styling
    working_dir: /app
    volumes:
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./project/project/static/Cms/input.css:/app/project/project/static/Cms/input.css
      - ./project/project/static/Cms/output.css:/app/project/project/static/Cms/output.css
      - ./project/page_manager/templates/Cms:/app/project/page_manager/templates/Cms
      - ./project/project/templates:/app/project/project/templates
      - ./project/login/templates:/app/project/login/templates
      - ./project/user/templates:/app/project/login/user
      - ./tailwindcss-linux-x64:/app/tailwindcss-linux-x64
    command: sh -c './tailwindcss-linux-x64 -i /app/project/project/static/Cms/input.css -o /app/project/project/static/Cms/output.css --minify' # yamllint disable-line
    # networks:
    #   - webnetwork
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prod/conf.d:/etc/nginx/conf.d/sarahisabella.info.conf
      - ./certs/:/etc/letsencrypt/
      - static:/static/
      - media:/media/
    ports:
      - 443:443
      - 80:80
      # networks:
      #   - webnetwork

volumes:
  postgres_data:
  media:
  static:
# networks:
#   dbnetwork:
#   webnetwork:
