--- # yamllint disable-line
version: "3.9"

services:
  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - dbnetwork
    restart: always
  website:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SITE=website
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    working_dir: /app/project
    volumes:
      - media:/app/project/media/
      - static:/app/project/static/
      - .:/app/
    command: sh -c 'python manage.py check && python manage.py runserver 0.0.0.0:8000' # yamllint disable-line
    ports:
      - "8002:8000"
    depends_on:
      - database
    restart: always
    links:
      - database:database
    networks:
      - dbnetwork
      - webnetwork
  cms:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SITE=cms
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    working_dir: /app/project
    volumes:
      - media:/app/project/media/
      - static:/app/project/static/
      - .:/app/
    command: sh -c 'python manage.py check && python manage.py runserver 0.0.0.0:8000' # yamllint disable-line
    ports:
      - "8001:8000"
    depends_on:
      - database
    links:
      - database:database
    restart: always
    networks:
      - dbnetwork
      - webnetwork
  cms-assets:
    build:
      context: ./
      dockerfile: Dockerfile.styling
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./project/project/static/Cms/input.css:/app/project/project/static/Cms/input.css
      - ./project/project/static/Cms/output.css:/app/project/project/static/Cms/output.css
      - ./project/page_manager/templates/Cms:/app/project/page_manager/templates/Cms
      - ./project/project/templates:/app/project/project/templates
      - ./project/login/templates:/app/project/login/templates
      - ./project/user/templates:/app/project/login/user
      - ./tailwindcss-linux-x64:/app/tailwindcss-linux-x64
    command: sh -c './tailwindcss-linux-x64 -i /app/project/project/static/Cms/input.css -o /app/project/project/static/Cms/output.css --watch --poll' # yamllint disable-line
    restart: always
    networks:
      - webnetwork
volumes:
  postgres_data:
  media:
  static:

networks:
  dbnetwork:
  webnetwork:
