from django.urls import path
from page_manager.views import (
    GetAllPagesApi,
    PageApi,
    PageDataApi,
    UploadImageApi,
    MovePageObjectApi,
    ChangeColumnAmount,
    UpdateComponentApi,
    GetPagePreviewApi,
    GetPageApi,
    UpdateSectionApi,
)

urlpatterns = [
    path(
        'api/pages/',
        GetAllPagesApi.as_view(),
        name='GetAllPagesApi'
    ),
    path(
        'api/pages/<slug>/',
        PageApi.as_view(),
        name='PageApi'
    ),
    path(
        'api/pages/<slug>/online/',
        GetPageApi.as_view(),
        name='GetPageApi'
    ),
    path(
        'api/page/<slug>/preview/',
        GetPagePreviewApi.as_view(),
        name='GetPagePreviewApi'
    ),
    path(
        'api/pages/<slug>/<object>/<index>/',
        PageDataApi.as_view(),
        name='PageDataApi'
    ),
    path(
        'api/pages/<slug>/<object>/move/<index>/<direction>/',
        MovePageObjectApi.as_view(),
        name='MovePageObjectApi'
    ),
    path(
        'api/pages/<slug>/column/change/<amount>/',
        ChangeColumnAmount.as_view(),
        name='ChangeColumnAmount'
    ),
    path(
        'api/pages/<slug>/component/update/<index>/',
        UpdateComponentApi.as_view(),
        name='UpdateComponentApi'
    ),
    path(
        'api/pages/<slug>/section/update/<index>/',
        UpdateSectionApi.as_view(),
        name='UpdateSectionApi'
    ),
    path(
        'api/image/',
        UploadImageApi.as_view(),
        name='UploadImageApi'
    ),
]
